# ?????????????????
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8        # ????/???????UTF-8
      force: true           # ????????/?????????????
      force-request: true   # ??????????
      force-response: true  # ??????????

# ?????
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hr_campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 549345

  # ????????????login.html?
  web:
    resources:
      static-locations: classpath:/static/
      index-page: login.html

  # JPA/Hibernate??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Jackson?????
  jackson:
    serialization:
      write-dates-as-timestamps: false